services:
  mongo:
    image: mongo:7
    container_name: syllasync-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./middle-tier-api
    container_name: syllasync-api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: SyllaSync_LocalDB
    env_file:
      - ./middle-tier-api/app/.env
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./middle-tier-api:/app

volumes:
  mongo_data: